- 15  # Основной свет
- 18  # Аэратор подстветка мощные диоды
- 23  # Помпа
- 24  # POWER GLO 40 Bт
- 25  # Сине-зелёная подсветка в крышке
- 8   # Подсветка в крышке ЛИНЗЫ
- 7   # Cиняя подстветка Тумбы
- 1   # Лампа Т5